# Generated by Django 2.2.2 on 2019-06-22 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='')),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('gid', models.CharField(max_length=30)),
                ('selected', models.BooleanField(default=False)),
                ('cites', models.ManyToManyField(related_name='_publication_cites_+', to='crystal.Publication')),
            ],
        ),
    ]
