# Generated by Django 2.2.2 on 2019-06-22 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crystal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='gid',
        ),
        migrations.AddField(
            model_name='publication',
            name='url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
