# Generated by Django 2.2.2 on 2019-06-22 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crystal', '0003_auto_20190622_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
