# Generated by Django 2.2.2 on 2019-06-28 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crystal', '0004_auto_20190622_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='cited_by_calculated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publication',
            name='cites_calculated',
            field=models.BooleanField(default=False),
        ),
    ]
