# Generated by Django 2.2.2 on 2019-06-28 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crystal', '0006_publication_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='cites',
            field=models.ManyToManyField(blank=True, related_name='cited_by', to='crystal.Publication'),
        ),
    ]
