# Generated by Django 3.0.5 on 2020-04-17 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crystal', '0009_auto_20190830_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='selected',
        ),
        migrations.AddField(
            model_name='publication',
            name='network_status',
            field=models.CharField(choices=[('INCLUDED', 'INCLUDED'), ('ARCHIVED', 'ARCHIVED'), ('UPLOADED', 'UPLOADED'), ('SUGGESTED', 'SUGGESTED')], default='SUGGESTED', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='active_network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crystal.Network'),
        ),
    ]
