# Generated by Django 3.0.5 on 2020-04-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crystal', '0010_auto_20200417_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='author',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='publication',
            name='file',
            field=models.FileField(blank=True, max_length=500, upload_to=''),
        ),
    ]
