# Generated by Django 3.0.5 on 2020-04-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crystal', '0011_auto_20200417_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='year',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
