# Generated by Django 3.0.5 on 2020-04-20 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crystal', '0013_auto_20200420_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='tags',
            field=models.ManyToManyField(blank=True, to='crystal.PublicationTag'),
        ),
    ]
