# Generated by Django 3.0.5 on 2020-04-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crystal', '0014_auto_20200420_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
