# Generated by Django 3.0.5 on 2020-04-21 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crystal', '0016_auto_20200421_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='category_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_pubs', to='crystal.PublicationTag'),
        ),
    ]
