# Generated by Django 3.0.5 on 2020-05-03 16:43

from django.db import migrations, models
import golgi.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('crystal', '0017_publication_category_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='file',
            field=models.FileField(blank=True, max_length=500, storage=golgi.storage_backends.PrivateMediaStorage(), upload_to=''),
        ),
    ]
